# Generated by Django 3.2.8 on 2021-10-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0003_rename_categoria_categoria_categori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categori',
            new_name='nombre',
        ),
    ]
