# Generated by Django 3.2.8 on 2021-10-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0006_auto_20211023_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.TextField(default='null'),
        ),
    ]
